### ISSUE TITLE
Could you please provide the platform key for system apk？

### ISSUE THREAD

**Issue by imlk0** [sonyxperiadev/release-keys#1]
I'm working on a project(an application) and I need to use the code `android:sharedUserId="android.uid.system"`
For some permission.

But it seems that the key I found here was not the correct one.
 Could you help me?
I need the correct platform.x509.pem and platform.pk8 files to sign my application. 

Thanks

**Comment by jerpelea** [comment]
please read Readme

those keys are used for the Open Devices Project
